// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAtAIjk6F0rPgJTqxpxVKi47lr-0_306o',
    appId: '1:742755751755:web:b0b9f7528902da85bd7ace',
    messagingSenderId: '742755751755',
    projectId: 'mailbx-a6227',
    authDomain: 'mailbx-a6227.firebaseapp.com',
    storageBucket: 'mailbx-a6227.appspot.com',
    measurementId: 'G-DQ3HVP5SQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTQ1r81dlxyu5URQcGncD4k87ccDpMu2k',
    appId: '1:742755751755:android:153b14abda11ee3bbd7ace',
    messagingSenderId: '742755751755',
    projectId: 'mailbx-a6227',
    storageBucket: 'mailbx-a6227.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-RwS2M57tAxweD5RVRK_ReQEt4pECbq8',
    appId: '1:742755751755:ios:ffa9a5697e3939adbd7ace',
    messagingSenderId: '742755751755',
    projectId: 'mailbx-a6227',
    storageBucket: 'mailbx-a6227.appspot.com',
    iosClientId: '742755751755-oijabsp02k9k1c2m2gbs5u6g3tis14kv.apps.googleusercontent.com',
    iosBundleId: 'app.mailbx.mailbx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-RwS2M57tAxweD5RVRK_ReQEt4pECbq8',
    appId: '1:742755751755:ios:24c381cb53c8b329bd7ace',
    messagingSenderId: '742755751755',
    projectId: 'mailbx-a6227',
    storageBucket: 'mailbx-a6227.appspot.com',
    iosClientId: '742755751755-rnmcdc2fvg2lug3kbh7bo02v78ke9khv.apps.googleusercontent.com',
    iosBundleId: 'com.example.mailapp01.RunnerTests',
  );
}
