// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAblLiBNrX1jkCdgVhvzh8I6qvIG_EPfPQ',
    appId: '1:879230167057:web:03f6f0751f09ec74d529b0',
    messagingSenderId: '879230167057',
    projectId: 'mailbx-andriod',
    authDomain: 'mailbx-andriod.firebaseapp.com',
    storageBucket: 'mailbx-andriod.appspot.com',
    measurementId: 'G-MMMQ9FM1K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV9HR_LPjJjixaNg_UVSU3Ecoq2A7RKyQ',
    appId: '1:879230167057:android:223b43db7a21a88bd529b0',
    messagingSenderId: '879230167057',
    projectId: 'mailbx-andriod',
    storageBucket: 'mailbx-andriod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcuKc6mcmiXTOFL2407nFXBqV6b_yr-H4',
    appId: '1:879230167057:ios:9bd47492d0abb713d529b0',
    messagingSenderId: '879230167057',
    projectId: 'mailbx-andriod',
    storageBucket: 'mailbx-andriod.appspot.com',
    iosClientId: '879230167057-9p78dbu3nu1bkdgkoq0sjsve1p8in32k.apps.googleusercontent.com',
    iosBundleId: 'com.example.mailapp01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcuKc6mcmiXTOFL2407nFXBqV6b_yr-H4',
    appId: '1:879230167057:ios:9c38320291d00cabd529b0',
    messagingSenderId: '879230167057',
    projectId: 'mailbx-andriod',
    storageBucket: 'mailbx-andriod.appspot.com',
    iosClientId: '879230167057-c02q8bj9l2e3fkgg4407h6amabuljjuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.mailapp01.RunnerTests',
  );
}
